### ISSUE TITLE
Error returned possibly after going idle

### ISSUE THREAD

**Issue by obrien-k** [code-noobs/slackbot#2]
0|index    | Channel is already closed can't broadcast error:
0|index    | TypeError: Converting circular structure to JSON
0|index    |     at Object.stringify (native)
0|index    |     at process.target._send (internal/child_process.js:671:23)
0|index    |     at process.target.send (internal/child_process.js:582:19)
0|index    |     at process.send (/usr/share/pm2/lib/ProcessContainer.js:51:21)
0|index    |     at process.uncaughtListener (/usr/share/pm2/lib/ProcessContainer.js:298:19)
0|index    |     at emitTwo (events.js:106:13)
0|index    |     at process.emit (events.js:191:7)
0|index    |     at emitPendingUnhandledRejections (internal/process/promises.js:66:22)
0|index    |     at process._tickDomainCallback (internal/process/next_tick.js:136:7)

After switching to axios.all instead of individual requests, the error is now giving a 525: SSL Handshake failed from Cloudflare so this may be due to the DNS API being used. Added some additional error handling with [2e097b9](https://github.com/code-noobs/slackbot/commit/2e097b910e3ca06c2ba85f42bfaa966b0b7c3837)

After some more research, the issue with it going idle after around 48 hours seems related to the Slackbots NPM module, namely [this issue](https://github.com/mishk0/slack-bot-api/issues/68). This appears to be addressed in the latest GitHub version and not on the latest NPM version. I've manually implemented this change with the latest version so we'll see if this is fixed (again).

**Comment by obrien-k** [comment]
I think this was being caused by a missing s in message on ~ line 72 when trying to handle an empty string. I'll need to see if this is something else over time though.

**Comment by obrien-k** [comment]
16 hours later, still running well. I'll give it a few more days before closing.

**Comment by obrien-k** [comment]
Slack went down and threw the data off, seems to be misbehaving so far unfortunately.


Edit: Slackbots 1.2.0 with ws-heartbeat fixed this
